export enum AppStorageMap {
  USER_INFO = 'userInfo',
  TOKEN = 'token',
  PRIVACY_POLICY_KEY = "0"
}


export enum RouterMap {
  LAUNCH_PAGE = 'LaunchPage',

  LAUNCH_AD_PAGE = 'LaunchAdPage',

  MAIN_ENTRY = 'MainEntry',

  PRIVACY_POLICY_PAGE = 'PrivacyPolicyPage',

  HOME_PAGE = 'HomePage',

  COURSE_PAGE = 'CoursePage',

  STUDY_PAGE = 'StudyPage',

  PROFILE_PAGE = 'ProfilePage',

  LOGIN_PAGE = 'LoginPage',

  COURSE_DETAIL_PAGE = 'CourseDetailPage',

  SEARCH_PAGE = 'SearchPage',

  MESSAGE_PAGE = 'MessagePage',

  MAIN_PAGE = "MainPage"
}